
export const appRoute = Object.freeze({
  dashboard: '/dashboard',
  instantMeeting: '/dashboard/rapat',
  instantMeetingV2: '/conference/room',
  webinar: '/dashboard/webinar',
  videoCall: '/conference/video-call',
  joinInstantMeeting: '/dashboard/rapat/join',
  document: '/dashboard/dokumen/semua',
  syllabus: '/dashboard/program/silabus',
  syllabusStatistic: '/dashboard/program/page-silabus-statistik',
  chat: '/dashboard/chat',
  chatVideo: '/dashboard/chat-dan-video',
  assigment: '/dashboard/bank-soal?section=soal',
  assigmentDetail: '/dashboard/bank-soal/detail/:id',
  assigmentCategory: '/dashboard/bank-soal?section=kategori',
  assigmentLog: '/dashboard/bank-soal/log',
  assigmentEdit: '/dashboard/bank-soal/ubah-soal/:id?section=soal',
  schedule: '/dashboard/jadwal',
  lastResult: '/dashboard/hasil-akhir',
  verifyStage2: '/auth/verify-stage-2',
  faceRegistration: '/auth/face-registration',
  user: {
    profile: '/dashboard/profile',
    registered: '/dashboard/pengguna/peserta/terdaftar',
    registeredDetail: '/dashboard/pengguna/peserta/terdaftar/detail/:id',
    applicant: '/dashboard/pengguna/peserta/pendaftar',
    applicantDetail: '/dashboard/pengguna/peserta/pendaftar/detail/:id',
    applicantVerifying: '/dashboard/pengguna/peserta/pendaftar/detail/verifikasi/:id',
    widyaiswara: '/dashboard/pengguna/widyaiswara',
    widyaiswaraDetail: '/dashboard/pengguna/widyaiswara/detail/:id',
    addWidyaiswara: '/dashboard/pengguna/widyaiswara/tambah',
    editWidyaiswara: '/dashboard/pengguna/widyaiswara/ubah/:id',
    add: '/dashboard/pengguna/peserta/tambah',
    edit: '/dashboard/pengguna/peserta/terdaftar/ubah/:id',
  },
  program: '/dashboard/program/program',
  programStatistic: '/dashboard/program/statistik',
  programParticipant: '/dashboard/program/program/detail/:id/peserta/:userId',
  trainee: '/dashboard/pelatihan',
  userManagement: {
    central: '/dashboard/manajemen-pengguna/pusat',
    user: '/dashboard/manajemen-pengguna/pengguna',
    userDetail: '/dashboard/manajemen-pengguna/pengguna/detail/:id',
    edit: '/dashboard/manajemen-pengguna/pengguna/ubah/:id',
    access: '/dashboard/manajemen-pengguna/akses',
  },
  master: {
    institution: '/dashboard/master/instansi',
    city: '/dashboard/master/wilayah/kota',
    province: '/dashboard/master/wilayah/provinsi',
    participantType: '/dashboard/master/tipe-peserta',
    holiday: '/dashboard/master/hari-libur',
    category: '/dashboard/master/kategori',
    position: '/dashboard/master/jabatan',
    group: '/dashboard/master/golongan',
  },
  templateCertificate: '/dashboard/template-sertifikat',
  notification: {
    all: '/dashboard/notifikasi',
    setting: '/dashboard/notifikasi/pengaturan',
  },
  participant: {
    list: '/dashboard/peserta',
    detail: '/dashboard/peserta/detail/:id',
    training: '/dashboard/peserta/detail/:id/pelatihan',
    violation: '/dashboard/peserta/detail/:id/pelanggaran',
  },
});